### ISSUE TITLE
Things to complete before 0.1.0 release

### ISSUE THREAD

**Issue by benbovy** [benbovy/xarray-simlab#11]
- [x] xarray extension API refactoring (#9)
- [x] add CONTRIBUTING file?
- [ ] ~~using default values (#10)~~ in a later release
- [x] DOC: write user guide chapters on how to inspect, setup/run and create models (#12)
- [x] DOC: write tests section in contributing
- [x] DOC: remaining todos (e.g., faq)
- [x] DOC: Add citation section + link in index
- [x] DOC: update installation and add a section for installing using pip or conda
- [x] DOC: update what's new section
- [x] Zenodo registration
- [x] Add Zenodo badge + citation link in README
- [x] update README (remove warning, doc is not a draft anymore)

**Comment by benbovy** [comment]
[ ] DOC: update what's new section
